DROP table user if EXISTS ;
CREATE table user (
  id bigint generated by DEFAULT AS identity,
  username VARCHAR(40),
  name VARCHAR(20),
  age int(3),
  balance DECIMAL(10,2),
  PRIMARY KEY (id)
  );